Add error handling around mod application (#939)
We have a production error in this area which is hard to debug:

```
ValueError: invalid literal for int() with base 10: '5“'

at ._apply_mods ( /app/gyrinx/core/models/list.py:1244 )
at .statline ( /app/gyrinx/core/models/list.py:1389 )
at .__get__ ( /opt/venv/lib/python3.12/site-packages/django/utils/functional.py:47 )
at ._resolve_lookup ( /opt/venv/lib/python3.12/site-packages/django/template/base.py:901 )
...
```